version: "3"

services:
    couchdb:
        image: couchdb:latest
        restart: always
        environment:
            - COUCHDB_USER=sigmund
            - COUCHDB_PASSWORD=re9ZP4zq
        volumes:
            - ./data:/usr/local/var/lib/couchdb
    xssprevent-test:
        build:
            context: .
            dockerfile: Dockerfile
        image: xssprevent-test:latest
        depends_on:
            - couchdb
        environment:
            - DESTINATION=127.0.0.1
            - PORT=80
            - COUCHDB_HOST=couchdb
            - COUCHDB_USER=sigmund
            - COUCHDB_PASSWORD=re9ZP4zq
        cap_add:
            - NET_ADMIN
            - NET_RAW          
        ports:
            - 8080:80
    dwva:
        image: vulnerables/web-dvwa:latest
        restart: always
        depends_on:
            - xssprevent-test
        ports:
            - 80:80

